global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using HarmonyLib;
global using JetBrains.Annotations;
global using UnityEngine;
global using static UnityEngine.Object;
global using Object = UnityEngine.Object;
global using Random = UnityEngine.Random;
global using ScriptableObject = UnityEngine.ScriptableObject;
global using static UnityEngine.ScriptableObject;
global using JFUtils;
global using JFUtils.WithPatch;
global using TheElectrician.Systems;
global using TMPro;
global using static JFUtils.ModBase;
global using static ZoneSystem;
global using static ZNetScene;
global using static ZoneSystem.ZoneLocation;
global using static ZoneSystem.ZoneVegetation;
global using static Heightmap;
global using static Heightmap.Biome;
global using static ItemDrop;
global using static ItemDrop.ItemData;
global using static TheElectrician.Plugin;
global using static BepInEx.BepInDependency;
global using static Skills;
global using ConsoleCommand = Terminal.ConsoleCommand;
global using static UnityEngine.Mathf;
global using StringBuilder = System.Text.StringBuilder;